# ----------------------------------------------------
# This config holds the Twitter configuration of the 
# server.
# Edit to set Twitter as live and then either reload
# or run updateConfig after altering to update settings
# ----------------------------------------------------
Twitter:
  TWITTER_CONFIGURED: false
  API_KEY: XXXX
  API_SECRET: YYYY
  token: ZZZ
  secret: ABABAB
