name: mineTwit
main: mineTwit.Main
version: {$VersionNumber}
commands:
   listNotification:
      description: This lists the current status of all notifications.
      usage: /listNotification 
      permission: op
      permission-message: No you don't, your level of omnipotency is sadly lacking!
   setNotification:
      description: This sets the status of any given notification.
      usage: /setNotification [Notification name] [Status]
      permission: op
      permission-message: No you don't, you just aren't worthy!
   updateMineTwitConfig:
      description: Updates the Twitter settings form the config file.
      usage: /updateMineTwitConfig
      permission: op
      permission-message: As if I'd let you do that!
